services:
  base:
    image: ${PREFIX}-dev-base
    build:
      context: ./base
    environment:
      - CONTAINER_NAME=${PREFIX}-dev-base
      - TERM=xterm-256color
    volumes: 
      - ${WORKSPACE_DIR}:/workspace
      - ./base/fish/fish_history:/root/.local/share/fish/fish_history

