services:
  base:
    image: ${PREFIX}-dev-base
    build:
      context: ./base
    environment:
      - CONTAINER_NAME=${PREFIX}-dev-base
      - TERM=xterm-256color
      - USE_COPILOT=${USE_COPILOT:-false}
    volumes:
      - ${WORKSPACE_DIR}:/workspace
      - ./base/fish/fish_history:/root/.local/share/fish/fish_history

  typescript:
    image: ${PREFIX}-dev-typescript
    build:
      context: ./typescript
      args:
        - BASE_IMAGE=${PREFIX}-dev-base
    environment:
      - CONTAINER_NAME=${PREFIX}-dev-rust
      - TERM=xterm-256color
      - USE_COPILOT=${USE_COPILOT:-false}
    volumes:
      - ${WORKSPACE_DIR}:/workspace

  rust:
    image: ${PREFIX}-dev-rust
    build:
      context: ./rust
      args:
        - BASE_IMAGE=${PREFIX}-dev-base
    environment:
      - CONTAINER_NAME=${PREFIX}-dev-rust
      - TERM=xterm-256color
      - USE_COPILOT=${USE_COPILOT:-false}
    volumes:
      - ${WORKSPACE_DIR}:/workspace
      - ./rust/fish/fish_history:/root/.local/share/fish/fish_history

  python:
    image: ${PREFIX}-dev-python
    build:
      context: ./python
      args:
        - BASE_IMAGE=${PREFIX}-dev-base
    environment:
      - CONTAINER_NAME=${PREFIX}-dev-python
      - TERM=xterm-256color
      - USE_COPILOT=${USE_COPILOT:-false}
    volumes:
      - ${WORKSPACE_DIR}:/workspace
      - ./python/fish/fish_history:/root/.local/share/fish/fish_history

